### PR TITLE
Promise rejection handler

### PR DESCRIPTION
**Pull request by corps**
This is the rollbar.js side of https://github.com/rollbar/node_rollbar/issues/61
Closed previous pull due to needing to fix the rebase off master.

Addressed @coryvirok 's remarks (unfortunately I can't carry them over here), and added more tests.  
Going to add docs and examples next.

### CODE REVIEW

**Comment by corps** [comment]
Embarrassing, got the pull wrong, this is what I get for rushing!  Closing this one, too.

**Comment by corps** [comment]
Ok, I fixed the history this time.  Should be one commit with the latest.

**Comment by corps** [comment]
Added documentation and get tests passing in travis.

**Comment by coryvirok** [comment]
Very nice. Merging and will get this into the next release.

**Pull request merged**
