### PR TITLE
Update dependencies to remove npm security warnings

### PR DESCRIPTION
**Pull request by waltjones**
- [x] update dependencies using `npm audit fix`
- [x] Solve remaining deps of deps that still have security warnings.

The latest versions of **grunt-cli, karma, webpack, babel-core, istanbul-instrumenter-loader, grunt-contrib-watch, grunt-webpack, and grunt-tagrelease** are each still affected by one or more of the following bulletins.
 https://npmjs.com/advisories/31
https://npmjs.com/advisories/996
https://npmjs.com/advisories/1012
 https://npmjs.com/advisories/1013
 https://npmjs.com/advisories/1065

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@waltjones Awesome!  I also see this adds `no-prototype-builtins` to the eslint config which seems like a great improvement 👍

I didn't look into all of these, but as far as I can tell `webpack@4.41.5` as one example shouldn't have any known vulnerabilities?  If some of Rollbar's dependencies do contain known vulnerabilities, could we use `npm shrinkwrap` to update the transitive dependencies mentioned in those alerts?

Alternately, since these alerts are sometimes noisy, if you're intentionally not patching these because you've audited how they interact with the codebase and don't think there's any meaningful risk, can you share more?  Also feel free to move this to another channel, I'm following your lead talking about it on Github 😄 

Thanks!

**Comment by waltjones** [comment]
Looks like I had stale node_modules. I just deleted node_modules, ran `npm install` again, and now I only get one warning (for grunt-tagrelease@0.3.3)
```
│ Moderate      │ Regular Expression Denial of Service                         │
│ Package       │ semver                                                       │
│ Patched in    │ >=4.3.2                                                      │
│ Dependency of │ grunt-tagrelease [dev]                                       │
│ Path          │ grunt-tagrelease > semver                                    │
│ More info     │ https://npmjs.com/advisories/31
```

New package-lock.json: https://github.com/rollbar/rollbar.js/pull/826

**Comment by kevinrobinson** [comment]
Great, thanks for checking up on this and building trust in Rollbar! 👍 

fwiw, [grunt-tagrelease](https://www.npmjs.com/package/grunt-tagrelease) is deprecated and last updated 6 years ago.  I couldn't find it being used anywhere, unless there's something  implicit happening ([https://github.com/rollbar/rollbar.js/search?q=grunt-tagrelease&unscoped_q=grunt-tagrelease}) so it seems like it might be possible to just remove it?  I don't know much more than grepping and scanning the README though :)

**Comment by waltjones** [comment]
I agree. I removed a bunch of dev deps in this PR. grunt-tagrelease looks like it can be removed too.

**Comment by waltjones** [comment]
https://github.com/rollbar/rollbar.js/pull/827

**Pull request merged**
