### PR TITLE
Update debug package to v2.6.9 to address Node Security Warning

### PR DESCRIPTION
**Pull request by robtarr**
https://nodesecurity.io/advisories/534

### CODE REVIEW

**Comment by coryvirok** [comment]
Thanks @robtarr. @rokob can you get this into the next release?

**Comment by rokob** [comment]
Yeah, looks good to me

**Comment by cordoval** [comment]
👍 superb thanks, eagerly waiting for a release!

**Comment by jtsaito** [comment]
Thank you! Could you please release the new tag quickly so that we can update our gazillion apps!

**Comment by rokob** [comment]
Just pushed out v2.2.9 which includes this, it takes a little while for cdnjs to propagate but should be available soon.

**Comment by jtsaito** [comment]
@rokob Thanks!

**Pull request merged**
