### PR TITLE
Replace http protocol to https on rollbarJsUrl config option.

### PR DESCRIPTION
**Pull request by jondeandres**

### CODE REVIEW

**Comment by coryvirok** [comment]
Seems like a bit of overkill for doing this. Can you think of anything else we would want to normalize in the config?

**Comment by jondeandres** [comment]
@coryvirok not actually, I can change it, but I thought it was a good ida having a isolated module to take care about the config format and others.

I'll change this.

**Comment by jondeandres** [comment]
@coryvirok I've replaced all that code with this https://github.com/rollbar/rollbar.js/commit/534f1e142fbcf6c8fe28b5b295fa8c04bf3428ac.

**Comment by coryvirok** [comment]
LGTM

**Comment by jondeandres** [comment]
@coryvirok what do you think?

@brianr for me that's fine, but I thought the problem exists when users sets by hand `rollbarJsUrl`.

**Comment by jondeandres** [comment]
The bad point I find is that this can be a problem developing mox, since the development server doesn't have ssl enabled no?

**Comment by brianr** [comment]
@jondeandres The purpose of this is to work around the issues we see where some proxies block OPTIONS requests (needed for CORS) when sent over HTTP. So forcing everything to go over HTTPS makes rollbar.js work out of the box for more clients.

For developing mox itself, you can still set `rollbarJsUrl` yourself to whatever you want. Though not if this PR is merged as-is :) That's my point - we should just change the default url to be https instead of schemaless.

**Comment by jondeandres** [comment]
Ok! I'll change this.

**Comment by jondeandres** [comment]
@brianr changed in https://github.com/rollbar/rollbar.js/commit/c2df60ffad9e128c4b0c20c8e96706b29f6a6228.

**Pull request merged**
