### PR TITLE
Actually honor NODE_ENV

### PR DESCRIPTION
**Pull request by djanowski**
Without this change, environment always reported as development.

### CODE REVIEW

**Comment by rokob** [comment]
Hah oh man that's terrible, my bad. 👍

**Comment by brianr** [comment]
Wouldn't this change mean that you can't specify the environment name explicitly? i.e. what if you want NODE_ENV to be a different value from the rollbar environment name?

**Comment by rokob** [comment]
No it gets picked up via

`this.options = _.extend(true, {}, Rollbar.defaultOptions, options);`

**Comment by djanowski** [comment]
Thank you!

**Pull request merged**
