### PR TITLE
Fix selenium issues

### PR DESCRIPTION
**Pull request by robertosanchez**
This adds the same fix as in `shim.js` to prevent the wrap function to crash when running with selenium.

Also, I updated `package.json` based on #116 to allow the build in travis to run correctly.

### CODE REVIEW

**Comment by robertosanchez** [comment]
@brianr @coryvirok any thought on this change? Does it look like a correct approach?

**Comment by brianr** [comment]
@robertosanchez Thanks for this! I'll defer to @coryvirok for the review on this change.

**Comment by coryvirok** [comment]
LGTM. I'll merge soon. I have another change I'd like to also get into the next release so I'll release a new version after that.

**Comment by robertosanchez** [comment]
Great! thanks!

**Pull request merged**
