### PR TITLE
Add public interface to serialize payloads and send serialized payloads

### PR DESCRIPTION
**Pull request by waltjones**
Fixes: https://github.com/rollbar/rollbar.js/issues/723

Adds two new API endpoints, allowing Rollbar event payloads to be captured as JSON, and delivered later. One example use case involves storing an exception event so it can be sent after app restart.

`buildJsonPayload()` accepts a `payload` object as provided in `checkIgnore()` for example, and returns a fully composed JSON string that can be stored or sent to the API as is.

`sendJsonPayload()` accepts the above string or any valid, fully prepared JSON string and sends to Rollbar API. 

The example (added to the webpack example) uses `checkIgnore()` to receive the `payload` object and build the JSON. This is a recommended place to hook this functionality because by returning `true` you can  prevent sending the stored payload.

### CODE REVIEW

**Comment by jjabba** [comment]
Thanks @waltjones! While I am using rollbar-react-native, I'm not actually using the wrapped Client, as I'm unable to link the native rollbar client while still using expo. I get around the initialization by importing and using import Client from 'rollbar/src/react-native/rollbar'

I've already prepared the checkIgnore hook in my configuration, looking forward to the PR making it into an actual release.

What is the release cadence?

**Comment by waltjones** [comment]
@jjabba this is now published in v2.6.0.

**Comment by jjabba** [comment]
@waltjones, that's great! I just upgraded to v2.6.0. Serialization works great. I'm able to save the payload in the checkIgnore hook. However, Im running into a problem while trying to use `rollbar.sendJsonPayload(serializedError)`. The error I'm getting is:
     
     this.transport.postJsonPayload is not a function (In 'this.transport.postJsonPayload(this.accessToken,n,t,s)', 'this.transport.postJsonPayload' is undefined)

I looked into it, and it seems rollbar-react-native comes with it's own version of the transport implementation: `node_modules/rollbar/src/react-native/transport.js` and it doesn't seem to include the postJsonPayload function in it's export

     module.exports = {
       get: get,
       post: post
     };



 The corresponding browserfile `node_modules/rollbar/src/browser/transport.js` however, does :

     module.exports = {
       get: get,
       post: post,
       postJsonPayload: postJsonPayload
     };

**Comment by waltjones** [comment]
@jjabba Sorry, I didn't see your comment until now. I will follow up shortly with another PR for this.

**Comment by waltjones** [comment]
@jjabba https://github.com/rollbar/rollbar.js/pull/725 is in release 2.6.1. Apologies for the inconvenience. Let me know if you have any issues.

**Pull request merged**
