### PR TITLE
turn sourceMaps on for uglify

### LINKED ISSUE #491: No source maps published for the .min.js dist bundles?
As per https://github.com/rollbar/rollbar.js/blob/626aac317d7879a3ecf62b71b0cadfa0dcc226b4/package.json#L10 I'm using `dist/rollbar.umd.min.js` in production. I just ran into a scenario where an error occurred in rollbar itself, and I discovered that there's no `sourceMappingURL` ref in the file and no `rollbar.umd.min.js.map` either.

Seems like that goes for *.min.js in the dist dir: https://github.com/rollbar/rollbar.js/tree/master/dist

I'm assuming this is by accident?

### PR DESCRIPTION
**Pull request by rokob**
Fixes #491

### CODE REVIEW

**Comment by papandreou** [comment]
@rokob, thanks for doing this! How about a new release with this change? 🙏

**Comment by papandreou** [comment]
@rokob, ping? Pretty please?

**Comment by rokob** [comment]
Ah yeah sorry will do.

**Comment by rokob** [comment]
I released v2.3.8 which has this change

**Comment by papandreou** [comment]
Thanks! Seems like the `//# sourceMappingURL=rollbar.umd.min.js.map` reference is missing from rollbar.umd.min.js, though? That makes it harder to get existing tools like https://github.com/webpack-contrib/source-map-loader to pick it up.

**Comment by rokob** [comment]
🤦‍♂️  https://github.com/rollbar/rollbar.js/pull/568

**Pull request merged**
